In [1]:
import pandas as pd

In [7]:
df = pd.read_csv('ai4i2020.csv')
df.shape

(10000, 14)

In [5]:
df.head()

,UDI,Product ID,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,HDF,PWF,OSF,RNF
0,1,M14860,M,298.1,308.6,1551,42.8,0,0,0,0,0,0,0
1,2,L47181,L,298.2,308.7,1408,46.3,3,0,0,0,0,0,0
2,3,L47182,L,298.1,308.5,1498,49.4,5,0,0,0,0,0,0
3,4,L47183,L,298.2,308.6,1433,39.5,7,0,0,0,0,0,0
4,5,L47184,L,298.2,308.7,1408,40.0,9,0,0,0,0,0,0

In [8]:
print(df.isnull().sum())

UDI                        0
Product ID                 0
Type                       0
Air temperature [K]        0
Process temperature [K]    0
Rotational speed [rpm]     0
Torque [Nm]                0
Tool wear [min]            0
Machine failure            0
TWF                        0
HDF                        0
PWF                        0
OSF                        0
RNF                        0
dtype: int64

In [ ]:
print(df.duplicated().sum())

0

In [11]:
print(df['Machine failure'].sum())

339

**Analysis of failure modes**

In [10]:
failure_columns = ["TWF", "HDF", "PWF", "OSF", "RNF"]
print(df[failure_columns].sum())

TWF     46
HDF    115
PWF     95
OSF     98
RNF     19
dtype: int64

1. HDF has the highest amount of failure.
2. RNF has the lowest amount of failure.
3. The sum of failure_columns compared to the sum of columns "Machine Failure" because many of these columns may have failed at the same row.

***Failure Rate By Product Type***

In [ ]:
df.groupby("Type")["Machine failure"].agg(
    ['count', 'sum', 'mean']
)

      count  sum      mean
Type
H      1003   21  0.020937
L      6000  235  0.039167
M      2997   83  0.027694

In [14]:
FailureRate = df.groupby("Type")["Machine failure"].mean()
print(FailureRate*100)

Type
H    2.093719
L    3.916667
M    2.769436
Name: Machine failure, dtype: float64